version: '2'
services:
  compilebox_api_server:
    build:
      context: .
      dockerfile: Dockerfile-server
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # use host Docker daemon
      - "results:${COMPILEBOX_RESULTS_DIR}"
    ports:
      - "${COMPILEBOX_API_SERVER_PORT}:${COMPILEBOX_API_SERVER_PORT}"
    depends_on:
      - compilebox
  compilebox:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile-vm
    command: echo "compilebox build complete"
    volumes:
      - "results:${COMPILEBOX_RESULTS_DIR}"
volumes:
  results:
