version: '2'
services:
  compilebox_api_server:
    build:
      context: .
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # use host Docker daemon
    ports:
      - "${COMPILEBOX_API_SERVER_PORT}:${COMPILEBOX_API_SERVER_PORT}"
    depends_on:
      - compilebox
  compilebox:
    env_file: .env
    build:
      context: ./Setup/
    command: echo "compilebox build complete"
