# --- multi-stage build 1/2: build api server from src ---
FROM golang:1.9-alpine as server

# GOPATH = /go in the golang image
# also $GOPATH/bin has been added to path

WORKDIR /go/src/github.com/frenata/compilebox

# copy API server src to be compiled
COPY . .

# compile and install server binary within container
RUN go install ./cmd/compilebox

# --- multi-stage build 2/2: install binaries onto clean image ---
FROM alpine

WORKDIR /bin/

# note that we must install Docker, but when we run the container, we must
# mount the /var/run/docker.sock of the host onto the container so the host
# docker daemon spins up sibling containers (as opposed to Docker in Docker)
RUN apk update && \
    apk add docker

# copy over single binary and supporting scripts from build stage --^
# TODO once compilebox uses the Docker native API we most likely won't need these supporting scritps
COPY --from=server /go/bin/compilebox .
COPY --from=server /go/src/github.com/frenata/compilebox/Payload ./Payload
COPY --from=server /go/src/github.com/frenata/compilebox/DockerTimeout.sh .

# copy compilers data
COPY ./data/compilers.json ./data/compilers.json

# run comilebox API server
CMD ["compilebox"]
